import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

const ROUTE = path.join(process.cwd(), "src/app/api/cron/sms-inbound-coach/route.ts");
const MIGRATION = path.join(
  process.cwd(),
  "supabase/migrations/20260327120000_sms_inbound_coach_jobs.sql"
);
const MIGRATIONS_DIR = path.join(process.cwd(), "supabase/migrations");
const WRITER = path.join(process.cwd(), "src/lib/inbound-sol-writer.ts");
const TURN = path.join(process.cwd(), "src/lib/inbound-sol-relationship-turn.ts");
const INTERPRETER = path.join(process.cwd(), "src/lib/inbound-sol-brief-interpreter.ts");
const TWILIO_INBOUND = path.join(process.cwd(), "src/app/api/twilio/inbound/route.ts");
const BURST_PACE = path.join(process.cwd(), "src/lib/sms-inbound-burst-pace.ts");

function solMainBlock(src: string): string {
  const start = src.indexOf("if (\n      isInboundSolMainCoachingBranch");
  const sent = src.indexOf("inbound_sol_main_sent", start);
  expect(start).toBeGreaterThan(0);
  expect(sent).toBeGreaterThan(start);
  return src.slice(start, sent + "inbound_sol_main_sent".length);
}

function solNoSendBlock(src: string): string {
  const block = solMainBlock(src);
  const noSend = block.indexOf("if (!solTurn.shouldSend || !solTurn.body?.trim())");
  const replyReady = block.indexOf('status: "reply_ready"');
  expect(noSend).toBeGreaterThan(0);
  expect(replyReady).toBeGreaterThan(noSend);
  return block.slice(noSend, replyReady);
}

function claimStatusLiterals(src: string): string[][] {
  const re = /\.in\(\s*"status"\s*,\s*\[([^\]]+)\]\s*\)/g;
  const out: string[][] = [];
  for (const m of src.matchAll(re)) {
    const inner = m[1];
    const statuses = [...inner.matchAll(/"([^"]+)"/g)].map((x) => x[1]);
    out.push(statuses);
  }
  return out;
}

function getHandler(src: string): string {
  const start = src.indexOf("export async function GET(req: Request)");
  expect(start).toBeGreaterThan(0);
  return src.slice(start);
}

describe("commit 2 — durable awaiting_manual_pat_answer job state", () => {
  const src = fs.readFileSync(ROUTE, "utf8");
  const turn = fs.readFileSync(TURN, "utf8");
  const writer = fs.readFileSync(WRITER, "utf8");
  const interpreter = fs.readFileSync(INTERPRETER, "utf8");
  const twilioInbound = fs.readFileSync(TWILIO_INBOUND, "utf8");
  const burstPace = fs.readFileSync(BURST_PACE, "utf8");
  const migration = fs.readFileSync(MIGRATION, "utf8");

  it("A: manual_pat_answer_needed parks the original job; reply_body null; no Twilio", () => {
    const noSend = solNoSendBlock(src);
    expect(noSend).toContain('solTurn.noSendReason === "manual_pat_answer_needed"');
    const manualStart = noSend.indexOf('solTurn.noSendReason === "manual_pat_answer_needed"');
    const elseIdx = noSend.indexOf("} else {", manualStart);
    const manual = noSend.slice(manualStart, elseIdx);
    expect(manual).toContain('status: "awaiting_manual_pat_answer"');
    expect(manual).toContain("replyBody: null");
    expect(manual).not.toContain('status: "cancelled"');
    expect(manual).not.toContain('status: "failed"');
    expect(manual).not.toContain('status: "needs_manual_review"');
    expect(manual).not.toContain("commitAndSendInboundCoachReply");
    expect(manual).not.toContain("sendSMSChunked");
    expect(noSend).not.toContain('.from("sms_inbound_coach_jobs")\n        .insert(');
    const solBlock = solMainBlock(src);
    expect(solBlock.indexOf("commitAndSendInboundCoachReply")).toBeGreaterThan(
      solBlock.indexOf('status: "reply_ready"')
    );
  });

  it("B: awaiting_manual_pat_answer is not in the cron claim IN-list", () => {
    const get = getHandler(src);
    const listIdx = get.indexOf(".in(\"status\", [\"pending\", \"failed\", \"reply_ready\"])");
    expect(listIdx).toBeGreaterThan(0);
    const claimIdx = get.indexOf(
      ".in(\"status\", [\"pending\", \"failed\", \"reply_ready\"])",
      listIdx + 1
    );
    expect(claimIdx).toBeGreaterThan(listIdx);
    expect(get).not.toContain("awaiting_manual_pat_answer");
    const literals = claimStatusLiterals(get);
    expect(literals.length).toBeGreaterThanOrEqual(2);
    for (const list of literals) {
      expect(list).toEqual(["pending", "failed", "reply_ready"]);
      expect(list).not.toContain("awaiting_manual_pat_answer");
      expect(list).not.toContain("cancelled");
      expect(list).not.toContain("needs_manual_review");
    }
  });

  it("C: pending manual job cannot be regenerated by retry / stale reclaim / processJob re-entry", () => {
    const get = getHandler(src);
    expect(get).toContain(".lt(\"attempt_count\", MAX_ATTEMPTS)");
    expect(src).toContain("const MAX_ATTEMPTS = 25");
    const reclaim = src.slice(
      src.indexOf("async function reclaimStaleJobs"),
      src.indexOf("async function loadJob")
    );
    expect(reclaim).toContain('.eq("status", "processing")');
    expect(reclaim).toContain('.eq("status", "generating_reply")');
    expect(reclaim).toContain('.eq("status", "sending")');
    expect(reclaim).not.toContain("awaiting_manual_pat_answer");

    const processStart = src.indexOf("async function processJob(claimedJob: JobRow)");
    const processEnd = src.indexOf("export async function GET(req: Request)");
    const processFn = src.slice(processStart, processEnd);
    expect(processFn).toContain('if (job.status === "awaiting_manual_pat_answer")');
    expect(processFn).toContain("inbound_sol_awaiting_manual_pat_answer_idempotent");
    const idempotentReturn = processFn.indexOf(
      'if (job.status === "awaiting_manual_pat_answer")'
    );
    expect(idempotentReturn).toBeGreaterThan(0);
    expect(processFn.indexOf("return;", idempotentReturn)).toBeGreaterThan(idempotentReturn);
    expect(processFn).not.toContain("runInboundSolRelationshipTurn");

    const failCatch = get.slice(get.indexOf("} catch (err)"));
    expect(failCatch).toContain('status: terminal ? "needs_manual_review" : "failed"');
    expect(failCatch).not.toContain("awaiting_manual_pat_answer");
    expect(failCatch).not.toContain("runInboundSolRelationshipTurn");

    const noSend = solNoSendBlock(src);
    const afterManualPark = noSend.slice(noSend.indexOf("replyBody: null"));
    expect(afterManualPark).not.toContain("await runInboundSolRelationshipTurn");
    expect(afterManualPark).not.toContain("writeInboundSolBody");
    expect(afterManualPark).not.toContain("commitAndSendInboundCoachReply");
  });

  it("D: generic Sol no-send still cancels exactly as before", () => {
    const noSend = solNoSendBlock(src);
    const elseIdx = noSend.indexOf("} else {");
    expect(elseIdx).toBeGreaterThan(0);
    const generic = noSend.slice(elseIdx);
    const genericMark = generic.slice(0, generic.indexOf("insertInboundTurnTelemetryBestEffort"));
    expect(genericMark).toContain('status: "cancelled"');
    expect(genericMark).toContain('tag: "inbound_sol_main_no_send"');
    expect(genericMark).toContain("nextRetry: farFutureIso()");
    expect(genericMark).not.toContain("replyBody:");
    expect(genericMark).not.toContain("awaiting_manual_pat_answer");
    expect(generic).not.toContain('status: "failed"');
    expect(generic).not.toContain('status: "needs_manual_review"');
    expect(noSend).toContain('solTurn.noSendReason === "manual_pat_answer_needed"');
  });

  it("E: failed retry behavior is unchanged", () => {
    const get = getHandler(src);
    expect(get).toContain('status: terminal ? "needs_manual_review" : "failed"');
    expect(get).toContain("computeNextRetryIso(nextAttempt)");
    expect(get).toContain("const terminal = nextAttempt >= MAX_ATTEMPTS");
    expect(get).toContain(".in(\"status\", [\"pending\", \"failed\", \"reply_ready\"])");
    expect(src).toContain("stale_processing_reclaimed");
    const reclaimProcessing = src.slice(
      src.indexOf("async function reclaimStaleJobs"),
      src.indexOf("async function loadJob")
    );
    expect(reclaimProcessing).toContain('status: "failed"');
    expect(reclaimProcessing).toContain('last_error: "stale_processing_reclaimed"');
  });

  it("F: normal grounded Pat reply still uses reply_ready then commitAndSend", () => {
    const block = solMainBlock(src);
    const noSendEnd = block.indexOf("return;", block.indexOf("if (!solTurn.shouldSend"));
    const sendPath = block.slice(noSendEnd);
    expect(sendPath).toContain("reply_body: solTurn.body");
    expect(sendPath).toContain('status: "reply_ready"');
    expect(sendPath).toContain('.eq("status", "processing")');
    expect(sendPath).toContain("commitAndSendInboundCoachReply");
    expect(sendPath).toContain("inbound_sol_main_sent");
    expect(sendPath).not.toContain("awaiting_manual_pat_answer");
    const sendClaim = src.slice(src.indexOf("async function commitAndSendInboundCoachReply"));
    expect(sendClaim).toContain('.eq("status", "reply_ready")');
    expect(sendClaim).toContain('status: "sending"');
  });

  it("G: NO/UNKNOWN ordinary inbound still cannot produce manual_pat_answer_needed", () => {
    expect(turn).toContain('noSend("writer_manual_pat_flag_without_yes"');
    expect(turn).toContain('requires_pat_personal_knowledge !== "yes"');
    const noSend = solNoSendBlock(src);
    expect(noSend).toContain('solTurn.noSendReason === "manual_pat_answer_needed"');
    const generic = noSend.slice(noSend.indexOf("} else {"));
    expect(generic).toContain('status: "cancelled"');
  });

  it("H: STOP / compliance short-circuit is unchanged", () => {
    const safetyFn = src.slice(
      src.indexOf("async function processInboundSmsSafetyShortCircuit"),
      src.indexOf("async function handleV2SmsInboundCoachJob")
    );
    expect(safetyFn).toContain("classifyInboundSmsSafetyTier");
    expect(safetyFn).toContain('status: "cancelled"');
    expect(safetyFn).not.toContain("awaiting_manual_pat_answer");
    expect(safetyFn).not.toContain("runInboundSolRelationshipTurn");
    expect(twilioInbound).toContain("isStopCommand(body)");
    const postStart = twilioInbound.indexOf("export async function POST");
    const postSlice = twilioInbound.slice(postStart);
    expect(postSlice.indexOf("isStopCommand(body)")).toBeLessThan(
      postSlice.indexOf("ensureCoachJobPresent")
    );
  });

  it("I: no new model calls in this slice", () => {
    const noSend = solNoSendBlock(src);
    expect(noSend).not.toContain("chat.completions");
    expect(noSend).not.toContain("writeInboundSolBody");
    expect(noSend).not.toContain("runInboundSolBriefInterpreter");
    expect(noSend).not.toContain("embeddings.create");
    expect(src.split("await runInboundSolRelationshipTurn({").length - 1).toBe(1);
    expect(turn.split("writeInboundSolBody({").length - 1).toBe(1);
    expect(turn.split("runInboundSolBriefInterpreter({").length - 1).toBe(1);
    expect(writer.split("chat.completions.create").length - 1).toBe(1);
    expect(interpreter.split("chat.completions.create").length - 1).toBe(1);
  });

  it("J: no email / admin / M/E/W behavior in this slice", () => {
    const noSend = solNoSendBlock(src);
    expect(noSend.toLowerCase()).not.toContain("resend");
    expect(noSend).not.toContain("admin");
    expect(noSend).not.toMatch(/\bmorning\b/i);
    expect(noSend).not.toMatch(/\bevening\b/i);
    expect(noSend).not.toMatch(/\bweekly\b/i);
    expect(src).not.toContain("from \"resend\"");
    expect(burstPace).not.toContain("awaiting_manual_pat_answer");
  });

  it("schema: status is unconstrained TEXT; no CHECK; no migration required", () => {
    expect(migration).toContain("status TEXT NOT NULL DEFAULT 'pending'");
    expect(migration).not.toMatch(/sms_inbound_coach_jobs[\s\S]{0,800}CHECK\s*\(\s*status/i);
    const files = fs.readdirSync(MIGRATIONS_DIR).filter((f) => f.endsWith(".sql"));
    for (const f of files) {
      const sql = fs.readFileSync(path.join(MIGRATIONS_DIR, f), "utf8");
      if (!sql.includes("sms_inbound_coach_jobs")) continue;
      expect(sql).not.toMatch(
        /ALTER TABLE(?:\s+public)?\.?sms_inbound_coach_jobs[\s\S]{0,400}CHECK\s*\(\s*status/i
      );
      expect(sql).not.toMatch(
        /sms_inbound_coach_jobs[\s\S]{0,200}ADD CONSTRAINT[\s\S]{0,200}status/i
      );
    }
  });

  it("telemetry uses existing last_error / log / compact no_send_reason seams only", () => {
    const manual = solNoSendBlock(src);
    expect(manual).toContain('tag: "inbound_sol_awaiting_manual_pat_answer"');
    expect(manual).toContain("[sms-inbound-coach] inbound_sol_awaiting_manual_pat_answer");
    expect(manual).toContain("insertInboundTurnTelemetryBestEffort");
    expect(manual).toContain("visibleSentIntended: false");
    expect(turn).toContain("inbound_sol_no_send_reason: noSendReason");
    expect(turn).toContain("no_send_reason: noSendReason");
    expect(src).not.toContain("create table");
    expect(src).not.toContain("from(\"sms_manual_pat");
  });
});
