-- Meta CAPI website match identifiers (StartTrial user_data).
-- Additive only. Does not modify Stripe, Apple, SMS, entitlement, or
-- marketing_attribution / marketing_events schemas.
-- Access: server-side service-role only. No client RLS policies.
-- No backfill. Identifier columns are nullable.
--
-- Retention: deleted with the Clerk account (see TypeScript purge helper).
-- No TTL cron in this slice. Do not keep these rows after account deletion.
-- Not used for auth, entitlement, identity ownership, or billing.
--
-- Account deletion (do not REPLACE the live purge_app_data_for_account_deletion
-- RPC here — replacing it from a historical copy can clobber production).
-- App-layer JS DELETE is backup; deletion must not complete while a row remains.
-- Exact live-RPC insert snippet:
--   supabase/migrations/20260909110000_meta_capi_web_identifiers_purge_rpc_snippet.sql
--   DELETE FROM public.meta_capi_web_identifiers WHERE clerk_user_id = v_clerk;
--   GET DIAGNOSTICS v_n = ROW_COUNT;
--   v_counts := v_counts || jsonb_build_object('meta_capi_web_identifiers', v_n);
--   v_total := v_total + v_n;
--
-- Rollback (before production rows exist):
--   DROP TABLE IF EXISTS public.meta_capi_web_identifiers;

CREATE TABLE public.meta_capi_web_identifiers (
  clerk_user_id TEXT PRIMARY KEY,
  meta_fbclid TEXT NULL,
  meta_fbclid_observed_at TIMESTAMPTZ NULL,
  meta_fbc TEXT NULL,
  meta_fbp TEXT NULL,
  client_ip TEXT NULL,
  client_user_agent TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT meta_capi_web_identifiers_clerk_user_id_nonempty_chk CHECK (
    length(trim(clerk_user_id)) > 0
  )
);

COMMENT ON TABLE public.meta_capi_web_identifiers IS
  'Website visitor match identifiers for Meta CAPI StartTrial. '
  'Keyed by Clerk user id (internal linkage only). '
  'Stores optional fbc/fbp/fbclid/IP/UA captured on web Stripe checkout. '
  'No names, emails, phone numbers, SMS bodies, goals, Ask Pat, Victory Room, or card data. '
  'Not for auth, entitlement, or billing. Service-role / server routes only. '
  'Deleted on account deletion. No automatic TTL cron.';

COMMENT ON COLUMN public.meta_capi_web_identifiers.meta_fbclid IS
  'Raw Meta fbclid query value first observed on a web marketing request. Nullable.';

COMMENT ON COLUMN public.meta_capi_web_identifiers.meta_fbclid_observed_at IS
  'Timestamp when meta_fbclid was first observed. Used if constructing fbc. Never webhook now.';

COMMENT ON COLUMN public.meta_capi_web_identifiers.meta_fbc IS
  'Exact _fbc cookie or Meta-documented construction from a real fbclid. Unhashed. Nullable.';

COMMENT ON COLUMN public.meta_capi_web_identifiers.meta_fbp IS
  'Exact _fbp cookie generated by Meta Pixel. Never fabricated. Unhashed. Nullable.';

COMMENT ON COLUMN public.meta_capi_web_identifiers.client_ip IS
  'Latest web create-checkout-session visitor IP from trusted Vercel headers. Not webhook IP.';

COMMENT ON COLUMN public.meta_capi_web_identifiers.client_user_agent IS
  'Latest web create-checkout-session visitor User-Agent. Not Stripe webhook UA.';

ALTER TABLE public.meta_capi_web_identifiers ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.meta_capi_web_identifiers FROM anon;
REVOKE ALL ON TABLE public.meta_capi_web_identifiers FROM authenticated;
REVOKE ALL ON TABLE public.meta_capi_web_identifiers FROM PUBLIC;
REVOKE ALL ON TABLE public.meta_capi_web_identifiers FROM service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.meta_capi_web_identifiers TO service_role;
